[a]
limbs = ["1", "0", "0"]

[b]
limbs = ["2", "0", "0"]

[c]
limbs = ["3", "0", "0"]

[d]
limbs = ["4", "0", "0"]

[e]
limbs = ["5", "0", "0"]

[expected]
limbs = ["43", "0", "0"]

[f]
limbs = ["6", "0", "0"]
