name: Noir Nightly Canary

on:
  schedule:
    # Run a check at 9 AM UTC
    - cron: "0 9 * * *"

env:
  CARGO_TERM_COLOR: always

permissions:
  issues: write

jobs:
  test:
    name: Test on Nargo ${{matrix.toolchain}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.3
        with:
          toolchain: nightly

      - name: Run Noir tests
        run: nargo test

      - name: Alert on dead links
        uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_NAME: ${{ github.workflow }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          update_existing: true
          filename: .github/NIGHTLY_CANARY_DIED.md
      